# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: spittet/php-postgresql

pipelines:
  default:
    - step:
        script:
          - composer install
          - composer require --dev symfony/phpunit-bridge
          - bin/console doctrine:schema:validate
          - ./vendor/bin/simple-phpunit
