<?php

namespace AppBundle\Repository;

/**
 * S3DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class S3DocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
