<?php

namespace AppBundle\Repository;

/**
 * SepaFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SepaFormRepository extends \Doctrine\ORM\EntityRepository
{
}
