# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }

    twig.extension.stringloader:
        class: Twig_Extension_StringLoader
        tags:
            - { name: twig.extension }

    app.aws.storageservice:
        class: AppBundle\Service\AWSSimpleStorageService
        arguments:
            credentials: ['%aws_access_key_id%', '%aws_secret_key%']
            region: %aws_s3_region%
            version: %aws_s3_version%
            bucket: %aws_s3_bucket%
            prefix: %aws_s3_prefix_key%
            currentEnv: %kernel.environment%

    app.eventlisteners.s3documentuploader:
        class: AppBundle\EventListener\S3DocumentUploader
        arguments: ["@app.aws.storageservice"]
        tags:
            - { name: doctrine.event_listener, event:preFlush }
#        arguments: ['@app.aws.storageservice']
